name: Push Notification

on:
  push:
    branches:
      - main
      - "dev*"
      - "test*"
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification email for PR
        uses: dawidd6/action-send-mail@v3
        with:
          
          server_address: smtp.gmail.com # SMTP server address
          server_port: 465 # SMTP server port
          username: ${{ secrets.EMAIL }} # Mail gönderilecek, mail adresi
          password: ${{ secrets.PASSWORD }} # Mail gönderilecek, mail adresinin şifresi ()
          to: ${{ secrets.EMAIL_TO }} # Mail gönderilecek, mail adresi
          from: ${{ secrets.EMAIL_FROM }} # Mail gönderen, mail adresi
          subject: "Push Notification fo PR - ${{github.event_name}}" # Mail konusu
          content_type: "text/html" # Mail içeriği
          body: |
            <table class="table table-striped">
                <caption>${{ github.event_name }} event triggered for PR</caption>
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Detail</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Repository:</td>
                        <td>${{ github.repository }}</td>
                    </tr>
                    <tr>
                        <td>Branch:</td>
                        <td>${{ github.ref }}</td>
                    </tr>
                    <tr>
                        <td>Event:</td>
                        <td>${{ github.event_name }}</td>
                    </tr>
                    <tr>
                        <td>Action:</td>
                        <td>${{ github.action }}</td>
                    </tr>
                    <tr>
                        <td>Actor:</td>
                        <td>${{ github.actor }}</td>
                    </tr>
                    <tr>
                        <td>Workflow:</td>
                        <td>${{ github.workflow }}</td>
                    </tr>
                    <tr>
                        <td>Run ID:</td>
                        <td>${{ github.run_id }}</td>
                    </tr>
                    <tr>
                        <td>Run Number:</td>
                        <td>${{ github.run_number }}</td>
                    </tr>
                    <tr>
                        <td>Event Name:</td>
                        <td>${{ github.event_name }}</td>
                    </tr>
                    <tr>
                        <td>Event Path:</td>
                        <td>${{ github.event_path }}</td>
                    </tr>
                    <tr>
                        <td>Event Inputs:</td>
                        <td>${{ github.event.inputs }}</td>
                    </tr>
                    <tr>
                        <td>Event Outputs:</td>
                        <td>${{ github.event.outputs }}</td>
                    </tr>
                    <tr>
                        <td>Event Payload:</td>
                        <td>${{ github.event.payload }}</td>
                    </tr>
                </tbody>
            </table> 